<!DOCTYPE html>
<!--
iTeam Project
You must abide by the copyright law of the people's Republic of China
and the protection of property right in your area,
and accept the terms of service of this website.
Without permit you are NOT allowed to modify this document.
-->
<html>
    <head>
        <title>系统登录 - iTeam纸飞机</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div><form action="../action/login.php" method="post">用户名<input name="una" type="text" required="required" />密码<input name="pws" type="password" required="required" /><input type="submit" name="登录" /></form></div>
    </body>
</html>
