<!DOCTYPE html>
<!--
iTeam Project
You must abide by the copyright law of the people's Republic of China
and the protection of property right in your area,
and accept the terms of service of this website.
Without permit you are NOT allowed to modify this document.
-->
<html>
    <head>
        <title>TODO supply a title</title>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
    </head>
    <body>
        <div><form><input /></form></div>
    </body>
</html>
