<!DOCTYPE html>
<html>
    <head>
        <title>创建帐户 - iTeam纸飞机</title>
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <style>
            .fon{
                font-family: "微软雅黑";
            }
            .headertitle{
                font-size: 30px;
            }
            .inputtextpass{
                width:600px;
                height:30px;
                border:2px #808080 solid;
            }
            .submitdata{
                width:280px;
                height:40px;
                font-size: 18px;
                color:#FFF;
                background-color: #0078d7;
            }
            .submitreset{
                width:280px;
                height:40px;
                font-size: 18px;
                color:#0078d7;
                background-color: #FFF;
            }
            a{
                text-decoration:none;   
            }
            a:link{
                color: #0078d7;
            }
            a:visited{
                color: #CCC;
            }
        </style>
    </head>
    <body>
    <script language=javascript>       
    function CharMode(iN){    
        if (iN>=48 && iN <=57)     
            return 1;    
        if (iN>=65 && iN <=90)    
            return 2;    
        if (iN>=97 && iN <=122)     
            return 4;    
        else    
            return 8;     
    }     
    function bitTotal(num){    
        modes=0;    
        for (i=0;i<4;i++){    
            if (num & 1) modes++;    
            num>>>=1;    
        }  
        return modes;    
    }  
    function checkStrong(sPW){    
        if (sPW.length<0)    
            return 0; 
        Modes=0;    
        for (i=0;i<sPW.length;i++){      
            Modes|=CharMode(sPW.charCodeAt(i));    
        }  
        return bitTotal(Modes);    
    }  
    function pwStrength(pwd){    
        Dfault_color="#eeeeee";
        L_color="#FF0000";
        M_color="#FF9900";
        H_color="#33CC00";
        if (pwd===null||pwd===''){    
            Lcolor=Mcolor=Hcolor=Dfault_color;  
        }    
        else{    
            S_level=checkStrong(pwd);    
            switch(S_level) {    
            case 0:    
                Lcolor=Mcolor=Hcolor=Dfault_color;  
                break;  
            case 1:    
                Lcolor=L_color;  
                Mcolor=Hcolor=Dfault_color;  
                break;    
            case 2:    
                Lcolor=Mcolor=M_color;    
                Hcolor=Dfault_color;    
                break;    
            default:    
                Lcolor=Mcolor=Hcolor=H_color;    
        }    
    }    
    document.getElementById("strength_L").style.background=Lcolor;    
    document.getElementById("strength_M").style.background=Mcolor;    
    document.getElementById("strength_H").style.background=Hcolor;    
    return;  
}  
</script> 
    <script>
          function validate() {
              var pw1 = document.getElementById("pw1").value;
              var pw2 = document.getElementById("pw2").value;
              if(pw1 == pw2) {
                  document.getElementById("tishi").innerHTML="<font color='green'>&nbsp;两次密码一致</font>";
                  document.getElementById("submit").disabled = false;
              }
              else {
                  document.getElementById("tishi").innerHTML="<font color='red'>&nbsp;两次密码不一致</font>";
                document.getElementById("submit").disabled = true;
              }
          }
      </script>
        <div class="fon">
            <div><p><div class="headertitle">创建帐户</div></div>
                <div><form action="../action/register.php" method="post">
                用户名<br/><br/><input class="inputtextpass" type="text" name="una" size="20" autofocus="autofocus" required="required" placeholder="请输入用户名"/><br/><br/>
                密码<br/><br/><input class="inputtextpass" type="password" name="pwd" size="20" required="required" placeholder="在此输入密码" id="pw1" onKeyUp=pwStrength(this.value) onBlur=pwStrength(this.value)/><table><tr align="center">  
            <td width="40" align="right">强度:</td>  
            <td width="50" id="strength_L" bgcolor="#eeeeee">弱</td>    
            <td width="50" id="strength_M" bgcolor="#eeeeee">中</td>    
            <td width="50" id="strength_H" bgcolor="#eeeeee">强</td>    
        </tr>
    </table> <br/>
                重新输入密码<br/><br/><input class="inputtextpass" type="password" name="pwdpwd" size="20" required="required" placeholder="在此输入密码" id="pw2" onkeyup="validate()"/><span id="tishi"></span><br/><br/>
                手机号码<br/><br/><input class="inputtextpass" type="text" name="tel" size="20" placeholder=""/><br/><br/>
                电子邮件地址<br/><input class="inputtextpass" type="email" name="email"/>
                <br/><br/>在继续之前，我们需要确认操作的是一个真实的人。<br/><br/> <img src="../library/IteamCaptcha.php" title="点击可刷新验证码" onclick="this.src='../library/IteamCaptcha.php'" /><br/><br/>
                <input type="text" class="inputtextpass" name="acd"  required="required"  placeholder="验证码"      />
                <br/><br/>单击“创建帐户”即表示你同意<a href="#"> iPush 服务协议</a>以及<a href="#">隐私和 Cookie 声明</a>。<br/><br/><br/>
                <input type="submit" name="submit" value="创建账户" class="submitdata" id="submit" />
                <input type="reset" name="reset" class="submitreset"     value="清除信息" />
            </form>
 
                </div>

        </div>
    </body>
</html>
